### ISSUE TITLE
multi-volume RAR support doesn't check file extensions

### ISSUE THREAD

**Issue by taxppnhoostzjegx** [notspiff/vfs.libarchive#21]
In a directory with the following files:
```
foo.aaa
foo.rar
foo.r00
foo.r01
```
`ArchiveCtx::Open` finds foo.rar, checks for and finds foo.r00, and then lists the directory to collect all the parts.

https://github.com/notspiff/vfs.libarchive/blob/fdc744118e9246ac7c6f58a1b8b47bd08a31013c/src/ArchiveFile.cpp#L116-L122

It looks for files with the right name (`fname`) but ignores file extensions, so it includes foo.aaa in the list of callbacks and gives libarchive a corrupted stream.

Adding something like `&& std::regex_match(it.Label(), std::regex(".+\\.r(ar|[0-9]+)$"))` to line 120 should fix the problem. It's still not a precise match on the filename but it's probably good enough.

**Comment by taxppnhoostzjegx** [comment]
Thanks for the fix!

One small point on the commit: I think that concatenating the filename into the regex might cause trouble down the road, since there's no escaping. I don't know if anyone actually puts `[]()` in their RAR file names though, and I think the rest are even less likely or harmless.

**Comment by notspiff** [comment]
hmm. i see your point. i will change to a two step process.

**Comment by notspiff** [comment]
done in https://github.com/notspiff/vfs.libarchive/commit/430a8e08b726880e2fba50686491564e1ca8a84d
